# Application Properties
# Application version
application.version=1.0.0
# Application description
application.description=Employee api for CRUD operations
#
#
#
#
#DB connection details
spring.datasource.url=jdbc:mysql://localhost:3306/employeedb
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

