owner-name: srivatsan

server:
  port: 8080
  servlet:
    context-path: /api/v1/employee

spring:
  application:
    name: employee
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
