server:
  port: 8080
  servlet.context-path: /${spring.application.name}/v1/

---
management:
  info.env.enabled: true
  endpoints:
    web.exposure.include: "*"
    prometheus.enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  application:
    name: employee
    version: 1.0.0
  profiles.active: ${SPRING_PROFILES_ACTIVE:postgres}
  banner.location: banner.txt
  cache.type: hazelcast
  jpa:
    hibernate.ddl-auto: none # create
    show-sql: true
    properties.hibernate:
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

  sql.init.mode: never # always
  output.ansi.enabled: always
  logging.level.org.hibernate.cache.spi: DEBUG

---
# Postgres properties
spring:
  config.activate.on-profile: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:5432/employees
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: postgres-con

---
# Application properties
global:
  debugModeEnabled: false