server:
  port: 8080
  servlet:
    context-path: /employee

spring:
  application:
    name: employee
  banner:
    location: banner.txt

  # Initialize Schema at StartUp
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
