CREATE DATABASE IF NOT EXISTS employeedb;
USE employeedb;

CREATE TABLE IF NOT EXISTS EMP_INFO (
  emp_id INT NOT NULL AUTO_INCREMENT,
  emp_name VARCHAR(15) DEFAULT NULL,
  emp_dept VARCHAR(15) DEFAULT NULL,
  emp_role VARCHAR(15) DEFAULT NULL,
  PRIMARY KEY (emp_id)
);
