version: "3.8"

services:
  employee_mysql:
    container_name: employee_mysql
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employeedb
    ports:
      - "3306:3306"

  employee:
    container_name: employee_app
    image: employee_app
    environment:
      - MYSQL_HOST=employee_mysql
      - MYSQL_PORT=3306
    ports:
      - "8080:8080"
    depends_on:
      - employee_mysql