version: "3.8"

services:
  mysql:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employeedb
    volumes:
      - /home/srivatsan/data:/var/lib/mysql
    ports:
      - "3307:3306"

  employee:
    image: emp_image
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    ports:
      - "8080:8080"
    depends_on:
      - mysql
